dist: xenial
language: python
python: 3.7
install: pip install awscli
script: make dist
jobs:
  include:
    - stage: deploy
      before_deploy: make dist
      deploy:
        provider: script
        script: make publish
